before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - test

build:amrex_2d-clang8:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:clang8
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-clang -o AMReX:dim=2 --build missing
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DFUB_WITH_OPENMP=False
    - make

build:amrex-2d_clang8_NO_EB:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:clang8
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-clang -o AMReX:dim=2 -o AMReX:eb=False --build missing
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DFUB_WITH_OPENMP=False
    - make

build:amrex-3d_clang8:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:clang8
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-clang -o AMReX:dim=3  --build missing
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DFUB_WITH_OPENMP=False
    - make

build:amrex-3d_clang8_NO_EB:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:clang8
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-clang -o AMReX:dim=3 -o AMReX:eb=False --build missing
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release -DFUB_WITH_OPENMP=False
    - make

build:amrex-2d_gcc9:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-gcc -o AMReX:dim=2 --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make

build:amrex-2d_gcc9_NO_EB:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-gcc -o AMReX:dim=2 -o AMReX:eb=False --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make

build:amrex-3d_gcc9:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-gcc -o AMReX:dim=3 --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make

build:amrex-3d_gcc9_NO_EB:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan install ../ --profile linux-gcc -o AMReX:dim=3 -o AMReX:eb=False --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make
