before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - test

build:amrex-2d_clang5:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_clang5
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++ -Wno-missing-braces" -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-2d_clang6:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_clang6
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-2d_clang7:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_clang7
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-2d_clang8:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_clang8
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-2d_gcc7:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_gcc7
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-2d_gcc8:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_gcc8
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-3d_gcc7:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:3d_gcc7
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make

build:amrex-3d_gcc8:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:3d_gcc8
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make
