variables:
  IMP_REGISTRY: git.imp.fu-berlin.de:5000

stages:
  - build

build_docker_images:
  stage: build
  image: $IMP_REGISTRY/pub/docker-git
  script:
    - cd docker/
    - bash build_images.sh