before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build
  - test

build:amrex-2d_gcc9:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install ../ -o AMReX:dim=2 -s compiler.libcxx=libstdc++11  --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make

build:amrex-3d_gcc9:
  image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:3d_gcc9
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install ../ -o AMReX:dim=3 -s compiler.libcxx=libstdc++11  --build missing
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug -DFUB_WITH_OPENMP=False
    - make