variables:
  IMP_REGISTRY: git.imp.fu-berlin.de:5000
  DOCKER_DRIVER: overlay2

stages:
  - build
  - install_conan_packages

.build_base: &build_base
  stage: build
  image: docker:git
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add bash
    - cd docker/
    - bash build_images.sh ${COMPILER_ID}
    - docker run conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}

build_clang8:
  variables:
    COMPILER_ID: "clang8"
  <<: *build_base

build_gcc9:
  variables:
    COMPILER_ID: "gcc9"
  <<: *build_base


#conan:amrex-2d_clang8:
  #image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_clang8
  #stage: install_conan_packages
  #script:
    #- conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}
    #- conan install "AMReX/20.04@ag-klein+FiniteVolumeSolver/stable" -o AMReX:dim="2" --build AMReX --env CXX=clang++ --env CC=clang

#conan:amrex-3d_clang8:
  #image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:3d_clang8
  #stage: install_conan_packages
  #script:
    #- conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}
    #- conan install "AMReX/20.04@ag-klein+FiniteVolumeSolver/stable" -o AMReX:dim="3" --build AMReX --env CXX=clang++ --env CC=clang

#conan:amrex-2d_gcc9:
  #image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:2d_gcc9
  #stage: install_conan_packages
  #script:
    #- conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}
    #- conan install "AMReX/20.04@ag-klein+FiniteVolumeSolver/stable" -o AMReX:dim="2" --build AMReX

#conan:amrex-3d_gcc9:
  #image: git.imp.fu-berlin.de:5000/ag-klein/finitevolumesolver/amrex:3d_gcc9
  #stage: install_conan_packages
  #script:
    #- conan user ci_user -r gitlab -p ${CI_JOB_TOKEN}
    #- conan install "AMReX/20.04@ag-klein+FiniteVolumeSolver/stable" -o AMReX:dim="3" --build AMReX
