variables:
  IMP_REGISTRY: git.imp.fu-berlin.de:5000
  DOCKER_DRIVER: overlay2
  
stages:
  - build

.build_base: &build_base
  stage: build
  image: docker:git
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add bash
    - cd docker/
    - bash build_images.sh ${COMPILER_ID} ${CI_JOB_TOKEN}

build_clang8:
  variables:
    COMPILER_ID: "clang8"
  <<: *build_base

build_gcc9:
  variables:
    COMPILER_ID: "gcc9"
  <<: *build_base
