function data = ReadHdf5DataN_PerfectGas(path, start, count)
  info = h5info(path);
  total_sizes = info.Datasets(2).Dataspace.Size;
  starts = ones(size(total_sizes));
  starts(end) = start;
  counts = [total_sizes(1:end-1) count];
  raw_data = h5read(path, '/data', starts, counts);
  sizes = size(raw_data);
  dx = h5readatt(path, '/data', 'cell_size');
  x0 = h5readatt(path, '/data', 'xlower');
  data.x = linspace(x0(1), x0(1) + (sizes(2) - 1)*dx(1), sizes(2));
  data.y = linspace(x0(2), x0(2) + (sizes(1) - 1)*dx(2), sizes(1));
  data.t = h5read(path, '/times', start, count);
  nx = length(data.x);
  ny = length(data.y);
  nt = sizes(4);
  data.rho = permute(reshape(raw_data(:,:,1,:), nx, ny, nt), [2 1 3]);
  data.u = permute(reshape(raw_data(:,:,2,:) ./ raw_data(:,:,1,:), nx, ny, nt), [2 1 3]);
  data.v = permute(reshape(raw_data(:,:,3,:) ./ raw_data(:,:,1,:), nx, ny, nt), [2 1 3]);
  data.rhoE = permute(reshape(raw_data(:,:,4,:), nx, ny, nt), [2 1 3]);
  data.p = permute(reshape(raw_data(:,:,5,:), nx, ny, nt), [2 1 3]);
  data.a = permute(reshape(raw_data(:,:,6,:), nx, ny, nt), [2 1 3]);
  data.M = sqrt(data.u .* data.u + data.v .* data.v) ./ data.a;
  R_specific = 287.1;
  data.T = data.p .* data.rho / R_specific;
  g = 1.4;
  data.p_t = data.p .* (1.0 + 0.5 * (g - 1.0) * data.M.^2).^(g / (g - 1.0)); 
end
