FROM ubuntu:22.04

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y python3-pip cmake g++ git python3 libopenmpi-dev

RUN pip3 install conan

RUN conan profile new --detect default && conan profile update settings.compiler.libcxx=libstdc++11 default

RUN git clone https://github.com/maikel/FiniteVolumeSolver.git /FiniteVolumeSolver

RUN conan create /FiniteVolumeSolver/conan/conan-amrex AMReX/development@local/stable

RUN conan create /FiniteVolumeSolver/conan/conan-hdf5 HDF5/1.10@local/stable

RUN conan create /FiniteVolumeSolver/conan/conan-vc Vc/1.4.3@local/stable